openapi: 3.0.4
info:
  title: Cashio API
  description: API for money transfer application.
  version: 0.1.9

servers:
  - url: http://localhost:3000
    description: Local development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/register:
    post:
      summary: Register a new user
      description: Creates a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                email:
                  type: string
                  format: email
                validatepassword:
                  type: string
                  format: password
                password:
                  type: string
                  format: password
                phoneNumber:
                  type: string
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Invalid request

  /auth/login:
    post:
      summary: Login an Existing User
      description: Authenticates a user and returns a token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        "200":
          description: User logged in successfully
        "400":
          description: Invalid request

  /auth/logout:
    post:
      summary: log out an Existing User.
      security:
        - bearerAuth: []
      description: log out a user and delete its token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: User logout  successfully
        "400":
          description: Invalid request

  /auth/refresh:
    post:
      summary: Refresh Authentication Token.
      security:
        - bearerAuth: []
      description: Refreshes the authentication token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        "200":
          description: Token refreshed successfully
        "400":
          description: Invalid or expired refresh token

  /transactions/send:
    post:
      summary: Send Money
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                receiverEmail:
                  type: string
                  format: email
                amount:
                  type: number
      responses:
        "200":
          description: Money sent successfully
        "400":
          description: Invalid request
        "404":
          description: User not found

  /transactions/all:
    get:
      summary: Get all transactions by user id.
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            example: 1

        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            example: 10

      responses:
        "200":
          description: list of transactions
        "404":
          description: User not found

  /transactions/{id}/accept:
    patch:
      summary: updates users wallet and users transaction
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: transaction id
          required: true
          schema:
            type: integer
            example: 10
      responses:
        "200":
          description: transaction was updated and money transfered
        "404":
          description: sonthing went wrong

  /transactions/{id}/reject:
    patch:
      summary: updates users wallet and users transaction
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: transaction id
          required: true
          schema:
            type: integer
            example: 10
      responses:
        "200":
          description: transaction was updated and money transfered
        "404":
          description: sonthing went wrong

  /wallet/myBalance:
    get:
      summary: Get Wallet Balance
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Wallet balance retrieved successfully
        "404":
          description: User not found
